services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot

  mailpit:
    image: axllent/mailpit:latest
    profiles: [dev]
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db:
  configdb:
  mongot:
