@baseUrl = http://localhost:8000
@username = user@example.com
@password = SecurePass123!
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjlmNzQ5ZmJiYjkwN2M5NzMzMzk3ZTg0IiwiZXhwIjoxNzc3ODI1NjQ2fQ.rOqXBhXdNbxviIWX5Ip5nEtJw3sRGY0oy4wCbOwcgGE

POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "email": "{{username}}",
  "password": "{{password}}",
  "full_name": "John Doe"
}

###
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "login": "{{username}}",
  "password": "{{password}}"
}

###
GET {{baseUrl}}/user/me
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "{{username}}"
}

###
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "token": "GcRoGWHH36xqfTYMKaJBiZrZN_MJAp7TINk3HatBUi8",
  "new_password": "{{password}}"
}

###
POST {{baseUrl}}/user/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "old_password": "{{password}}",
  "new_password": "NewSecurePass123!"
}
