@baseUrl = http://localhost:8000
@username = user@example.com
@password = SecurePass123!

POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "email": "{{username}}",
  "password": "{{password}}",
  "full_name": "John Doe"
}

###
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "login": "{{username}}",
  "password": "{{password}}"
}

###
GET {{baseUrl}}/user/me
