@baseUrl = http://localhost:8000
@username = user@example.com
@password = SecurePass123!
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjlmNzQ5ZmJiYjkwN2M5NzMzMzk3ZTg0IiwiZXhwIjoxNzc3ODE3NjQ5fQ.115yPklN4xXs8xiwZYfrnNjl2SgDKzAlSz3bDdVtqP4

POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "email": "{{username}}",
  "password": "{{password}}",
  "full_name": "John Doe"
}

###
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "login": "{{username}}",
  "password": "{{password}}"
}

###
GET {{baseUrl}}/user/me
Authorization: Bearer {{token}}
